stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data/processed
    params:
      - prepare.test_size
  train:
    cmd: python src/train.py
    deps:
    - data/processed
    - src/train.py
    outs:
    - model.pkl
    - metrics.json
    params:
      - train.n_estimators
      - train.random_state
